live_config_reload = true

[window]
dimensions = { columns = 200, lines = 60 }
padding = { x = 8, y = 4 }
opacity = 0.85

[cursor]
style = "Beam"

[scrolling]
history = 100000
multiplier = 3


[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]
