live_config_reload = true

[window]
dimensions = { columns = 200, lines = 60 }
padding = { x = 8, y = 4 }
opacity = 0.85

[cursor]
style = "Beam"

[scrolling]
history = 100000
multiplier = 3

import = [
  "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]